; ESP-Guard orchestrator / gateway
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
	'-D DEVICE_DEFAULT_NAME="Orchestrator"'
	'-D DEFAULT_POST_URL=""'
	-D BUILTIN_LED_PIN=2
	-D PORTAL_PIN=0
lib_extra_dirs =
	../../shared
lib_deps =
	pangodream/ESP2SOTA@^1.0.2
	witnessmenow/UniversalTelegramBot@^1.3.0
